// This code snippet was auto generated by xls2vlog.py from source file: /home/patrick/Downloads/Interface-Definition.xlsx
// User: patrick
// Date: Jun-15-23



module AXIL_AXIS #( parameter pADDR_WIDTH   = 12,
                    parameter pDATA_WIDTH   = 32
                  )
(
  output wire          m_awvalid,
  output wire  [31: 0] m_awaddr,
  output wire          m_wvalid,
  output wire  [31: 0] m_wdata,
  output wire   [3: 0] m_wstrb,
  output wire          m_arvalid,
  output wire  [31: 0] m_araddr,
  output wire          m_rready,
  output wire  [31: 0] s_rdata,
  output wire          s_rvalid,
  output wire          s_awready,
  output wire          s_wready,
  output wire          s_arready,
  input  wire          s_awvalid,
  input  wire  [14: 0] s_awaddr,
  input  wire          s_wvalid,
  input  wire  [31: 0] s_wdata,
  input  wire   [3: 0] s_wstrb,
  input  wire          s_arvalid,
  input  wire  [14: 0] s_araddr,
  input  wire          s_rready,
  input  wire  [31: 0] m_rdata,
  input  wire          m_rvalid,
  input  wire          m_awready,
  input  wire          m_wready,
  input  wire          m_arready,
  input  wire          cc_aa_enable,
  input  wire  [31: 0] as_aa_tdata,
  input  wire   [3: 0] as_aa_tstrb,
  input  wire   [3: 0] as_aa_tkeep,
  input  wire          as_aa_tlast,
  input  wire          as_aa_tvalid,
  input  wire   [1: 0] as_aa_tuser,
  output  wire         aa_as_tready,
  output wire  [31: 0] aa_as_tdata,
  output wire   [3: 0] aa_as_tstrb,
  output wire   [3: 0] aa_as_tkeep,
  output wire          aa_as_tlast,
  output wire          aa_as_tvalid,
  output wire   [1: 0] aa_as_tuser,
  input  wire          as_aa_tready,
  output wire          mb_irq,
  input  wire          axi_clk,
  input  wire          axi_reset_n,
  input  wire          axis_clk,
  input  wire          axis_rst_n
);

  reg m_awvalid=0;
  reg  [31: 0] m_awaddr=0;
  reg          m_wvalid=0;
  reg  [31: 0] m_wdata=0;
  reg   [3: 0] m_wstrb=0;
  reg          m_arvalid=0;
  reg  [31: 0] m_araddr=0;
  reg          m_rready=0;
  reg  [31: 0] s_rdata=0;
  reg          s_rvalid=0;
  reg          s_awready=0;
  reg          s_wready=0;
  reg          s_arready=0;
  reg aa_as_tready=0;
  reg  [31: 0] aa_as_tdata=0;
  reg   [3: 0] aa_as_tstrb=0;
  reg   [3: 0] aa_as_tkeep=0;
  reg          aa_as_tlast=0;
  reg          aa_as_tvalid=0;
  reg   [1: 0] aa_as_tuser=0;
  reg          mb_irq=0;
endmodule // AXIL_AXIS
